### ISSUE TITLE
Run Python and minor issues

### ISSUE THREAD

**Issue by anonimo82** [vhqtvn/VHEditor-Android#44] opened 2021-02-06 14:22 UTC
Hello everyone, I didn't understand how to run Python code from this.
Terminal won't open, and some menu items don't work (like, in example, file -> open folder)

I'd like to stick with this fully featured editor, I've been looking for something similar for ages.

Thanks in advance for any help.

Bye, Ivano.

**Comment by anonimo82** [comment] 2021-02-06 17:38
Ok, don't know how, but now terminal and what wasn't working, works ok.
But, on terminal, trying to even just doing a "pkg update", this is what happens:

```$ pkg update
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Warning: aborting execution because /data/data/com.termux/files/usr is not accessible.
Please make sure that program is compiled with correct prefix.
$ ```

**Comment by anonimo82** [comment] 2021-02-09 20:46
Anyone?

**Comment by anonimo82** [comment] 2021-02-14 18:42
Bumo

**Comment by anonimo82** [comment] 2021-02-20 06:14
Still waiting for help...

**Comment by anonimo82** [comment] 2021-03-10 07:39
Hey

**Comment by anonimo82** [comment] 2021-04-12 10:01
@vhqtvn help

**Comment by vhqtvn** [comment] 2021-04-13 14:52
Sorry i has been too busy recently, dont have time left for this project :( The problem is due to termux to implement checks that prevent non-termux applications to use their packages, i'm trying to build my own repository but it need time...

**Comment by anonimo82** [comment] 2021-04-13 15:30
Ok, please, keep me updated

**Comment by vhqtvn** [comment] 2021-05-24 23:52
Hi, please try the latest version now, the problem should be fixed.

**Closed by vhqtvn** 2021-05-24 23:52 UTC

**Comment by anonimo82** [comment] 2021-05-25 05:14
No, I can't neither run the editor now.
